### ISSUE TITLE
Expected a JavaScript module script

### ISSUE THREAD

**Issue by glad2os** [tiangolo/node-frontend#19]
Google chrome logs:

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

default config:
```
server {
    listen 5173;

    location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
    }

    include /etc/nginx/extra-conf.d/*.conf;

}

```

```
# Build stage
FROM node:20.11 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]

```

**Comment by tiangolo** [comment]
Hello there!

I no longer use nor recommend this Docker image, I think you are much better off building a Docker image yourself, so I updated all the docs to explain how to do it: https://github.com/tiangolo/node-frontend

The only extra step is creating and copying a simple `nginx.conf` file that you can copy-paste.

Given that, I'll now close this one. But thanks for the interest! :coffee:
