### ISSUE TITLE
Upgrade node version

### ISSUE THREAD

**Issue by AlanCrevon** [tiangolo/node-frontend#2]
Hi @tiangolo !

Thanks for this  image which is now part of my workflow :+1: 

I think it would be nice to get node 11 and node 12 versions for this image. I don't think it requires a lot of modifications, but i don't know how to test everything works as expected with non latin characters (working from France on european projects only).

**Comment by tiangolo** [comment]
Thanks, good idea. I'll try to do it.

**Comment by frjtrifork** [comment]
Angular CLI 8+ also does not work with the current release in Docker hub. It uses Node 10.5 - but Angular CLI 8 requires 10.9 or later (latest today is 10.16). 
It would be great if you could make a new/updated build of the current version also.

**Comment by Fhrost0213** [comment]
Ran into the same issue today trying to upgrade Angular and realizing the latest version of this image doesn't support Angular 8+

**Comment by tiangolo** [comment]
Thanks! And sorry for the long delay. :see_no_evil: 

I no longer use nor recommend this Docker image, I think you are much better off building a Docker image yourself, so I updated all the docs to explain how to do it: https://github.com/tiangolo/node-frontend

The only extra step is creating and copying a simple `nginx.conf` file that you can copy-paste.

Given that, I'll now close this one. But thanks for the interest! :coffee:
