### ISSUE TITLE
issues in pulling image id : dd4fcf0b263b:

### ISSUE THREAD

**Issue by plrsght2** [tiangolo/node-frontend#3]
Getting "retrying in 1 sec" docker error for this image

**Comment by plrsght2** [comment]
![image](https://user-images.githubusercontent.com/63811458/79570608-6475ff00-80d7-11ea-9e50-b27872c751a6.png)

**Comment by plrsght2** [comment]
Restarted Docker and it worked.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
