### ISSUE TITLE
There were unauthenticated packages and -y was used without --allow-unauthenticated

### ISSUE THREAD

**Issue by johnico** [tiangolo/node-frontend#4]
Hi. I got this error after apt get update , 
 fixed with --force-yes but I guess there is an issue in the base docker file ? 

```
WARNING: The following packages cannot be authenticated!
  libssl1.0.2 krb5-locales libgmp10 libnettle6 libhogweed4 libidn11 libffi6
  libp11-kit0 libtasn1-6 libgnutls30 libkeyutils1 libkrb5support0 libk5crypto3
  libkrb5-3 libgssapi-krb5-2 libsasl2-modules-db libsasl2-2 libldap-common
  libldap-2.4-2 openssl ca-certificates libunistring0 libidn2-0 libnghttp2-14
  libpsl5 librtmp1 libssh2-1 libcurl3 curl libsasl2-modules publicsuffix
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command '/bin/sh -c apt-get install -y curl' returned a non-zero code: 100
```

```
# Base on "tiangolo/node-frontend:10"
FROM tiangolo/node-frontend:10 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
ARG configuration=production
RUN npm run build -- --output-path=./dist/out --configuration $configuration

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.15

RUN apt-get update
RUN apt-get install -y --force-yes curl

# Copy dist
COPY --from=build-stage /app/entrypoint.sh /

COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html
# Copy default nginx.conf
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
CMD ["/bin/bash",  "-c", "/entrypoint.sh && exec nginx -g 'daemon off;'"]
```

**Comment by chris-allnutt** [comment]
The base image is DebianStretch.   It's generally ok to run apt-get update, and install a specific package, I wouldn't recommend doing apt-get install without a specific package in a docker container as you could end up with breaking changes you didn't intend.

I would guess that the image does not have the certificates installed, or they aren't updated.  I will say I didn't have a problem using curl.

**Comment by tiangolo** [comment]
Thanks! And sorry for the long delay. :see_no_evil: 

I no longer use nor recommend this Docker image, I think you are much better off building a Docker image yourself, so I updated all the docs to explain how to do it: https://github.com/tiangolo/node-frontend

The only extra step is creating and copying a simple `nginx.conf` file that you can copy-paste.

Given that, I'll now close this one. But thanks for the interest! :coffee:
