### ISSUE TITLE
bump node version

### ISSUE THREAD

**Issue by urbanoTF** [tiangolo/node-frontend#8]
Gatsby is having build issues with the node version of this image.

"Gatsby requires Node.js 12.13.0 or higher (you have v1***5.3)."

Fixed with #7

**Comment by tiangolo** [comment]
Thanks! And sorry for the long delay. :see_no_evil: 

I no longer use nor recommend this Docker image, I think you are much better off building a Docker image yourself, so I updated all the docs to explain how to do it: https://github.com/tiangolo/node-frontend

The only extra step is creating and copying a simple `nginx.conf` file that you can copy-paste.

Given that, I'll now close this one. But thanks for the interest! :coffee:
